"""Constants for Zentec 031 integration."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "zentec031"

CONF_SLAVE_ID = "slave_id"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_POWER_REGISTER = "power_register"
CONF_MODE_REGISTER = "mode_register"
CONF_MODE_HEAT_VALUE = "mode_heat_value"
CONF_MODE_VENT_VALUE = "mode_vent_value"
CONF_FAN_SPEED_REGISTER = "fan_speed_register"
CONF_TARGET_TEMP_REGISTER = "target_temp_register"
CONF_MIN_HEAT_TEMP_REGISTER = "min_heat_temp_register"
CONF_MAX_HEAT_TEMP_REGISTER = "max_heat_temp_register"
CONF_SUPPLY_TEMP_REGISTER = "supply_temp_register"
CONF_SUPPLY_TEMP_DIVISOR = "supply_temp_divisor"
CONF_OUTDOOR_TEMP_REGISTER = "outdoor_temp_register"
CONF_ALARM_REGISTER = "alarm_register"
CONF_TEMPERATURE_DIVISOR = "temperature_divisor"
CONF_MAX_FAN_SPEED = "max_fan_speed"
CONF_READ_ONLY = "read_only"

DEFAULT_PORT = 502
DEFAULT_SLAVE_ID = 0
DEFAULT_SCAN_INTERVAL = 10

# Defaults from docs/params.xlsx (Table 8 + parameter map).
DEFAULT_POWER_REGISTER = 40003
DEFAULT_MODE_REGISTER = 40001
DEFAULT_MODE_HEAT_VALUE = 2
DEFAULT_MODE_VENT_VALUE = 1
DEFAULT_FAN_SPEED_REGISTER = 40000
DEFAULT_TARGET_TEMP_REGISTER = 40002
DEFAULT_MIN_HEAT_TEMP_REGISTER = 50008
DEFAULT_MAX_HEAT_TEMP_REGISTER = 50009
DEFAULT_SUPPLY_TEMP_REGISTER = 40009
DEFAULT_SUPPLY_TEMP_DIVISOR = 10
DEFAULT_OUTDOOR_TEMP_REGISTER = 50005
DEFAULT_ALARM_REGISTER = 40004
DEFAULT_TEMPERATURE_DIVISOR = 1
DEFAULT_MAX_FAN_SPEED = 7
DEFAULT_READ_ONLY = False

DEFAULT_UPDATE_INTERVAL = timedelta(seconds=DEFAULT_SCAN_INTERVAL)

PLATFORMS = ["climate", "number", "sensor"]

OPTION_KEYS = {
    CONF_POWER_REGISTER,
    CONF_MODE_REGISTER,
    CONF_MODE_HEAT_VALUE,
    CONF_MODE_VENT_VALUE,
    CONF_FAN_SPEED_REGISTER,
    CONF_TARGET_TEMP_REGISTER,
    CONF_MIN_HEAT_TEMP_REGISTER,
    CONF_MAX_HEAT_TEMP_REGISTER,
    CONF_SUPPLY_TEMP_REGISTER,
    CONF_SUPPLY_TEMP_DIVISOR,
    CONF_OUTDOOR_TEMP_REGISTER,
    CONF_ALARM_REGISTER,
    CONF_TEMPERATURE_DIVISOR,
    CONF_MAX_FAN_SPEED,
    CONF_READ_ONLY,
    CONF_SCAN_INTERVAL,
}
